services:
  platform:
    image: ghcr.io/adrianliechti/wingman-platform
    pull_policy: always
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - REPLICATE_API_KEY=${REPLICATE_API_KEY}

      - EXA_API_KEY=${EXA_API_KEY}
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    volumes:
      - ./config.yaml:/config.yaml:ro
      - ./public:/public
      - ./prompts:/prompts
  chat:
    image: ghcr.io/adrianliechti/wingman-chat
    pull_policy: always
    restart: unless-stopped
    environment:
      - TITLE=FastIT AI
      - WINGMAN_URL=http://platform:8080
      - TTS_ENABLED=true
      - STT_ENABLED=true
      - VOICE_ENABLED=true
      - VISION_ENABLED=true
      - IMAGE_ENABLED=true
      - INTERNET_ENABLED=true
      - INTERNET_INDEX=exa
      - INTERNET_EXTRACTOR=exa
      - ARTIFACTS_ENABLED=true
      - REPOSITORY_ENABLED=true
      - REPOSITORY_EMBEDDER=text-embedding-3-small
      - REALTIME_PROXY=http://realtime:8080
    volumes:
      - ./models.yaml:/app/models.yaml
      - ./translator.yaml:/app/translator.yaml
    ports:
      - 8000:8000
    depends_on:
      - platform
#      - chat-auth
#for voice mode
  realtime:
    image: ghcr.io/adrianliechti/wingman-realtime-proxy
    pull_policy: always
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
#Internet fetching
  reader:
    image: ghcr.io/adrianliechti/wingman-reader
    pull_policy: always
    restart: unless-stopped

  segmenter:
    image: ghcr.io/adrianliechti/wingman-segmenter
    pull_policy: always
    restart: unless-stopped

  extractor:
    image: ghcr.io/adrianliechti/wingman-extractor
    pull_policy: always
    restart: unless-stopped


